package com.example.resturantapp.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.example.resturantapp.dto.OrderItemDTO;
import com.example.resturantapp.models.OrderItem;
import com.example.resturantapp.models.MenuItem;
import com.example.resturantapp.models.Order;

@Mapper(componentModel = "spring")
public interface OrderItemMapper {

    @Mapping(source = "menuitem.menuitemid", target = "menuitemid")
    @Mapping(source = "menuitem.menuitemname", target = "menuitemname")
    @Mapping(source = "portiontype", target = "portiontype")
    @Mapping(source = "order.orderid", target = "orderid") // map order reference
    @Mapping(target = "orderitemid", ignore = true) // usually auto-generated by DB
    OrderItemDTO toDTO(OrderItem orderitem);

    List<OrderItemDTO> toDTOList(List<OrderItem> orderitems);

    @Mapping(source = "menuitemid", target = "menuitem.menuitemid")
    @Mapping(source = "orderid", target = "order.orderid")
    @Mapping(target = "orderitemid", ignore = true)
    OrderItem toEntity(OrderItemDTO orderitemDTO);

    // Optional helpers if needed
    default MenuItem mapMenuItemIdToMenuItem(Long menuitemid) {
        if (menuitemid == null)
            return null;
        MenuItem m = new MenuItem();
        m.setMenuitemid(menuitemid);
        return m;
    }

    default Order mapOrderIdToOrder(Long orderid) {
        if (orderid == null)
            return null;
        Order o = new Order();
        o.setOrderid(orderid);
        return o;
    }
}
